# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excelerror.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 237)
        MainWindow.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"background-color: rgb(85, 85, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 311, 31))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.intcortes = QtWidgets.QTextEdit(self.centralwidget)
        self.intcortes.setGeometry(QtCore.QRect(340, 20, 261, 31))
        self.intcortes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.intcortes.setObjectName("intcortes")
        self.boton = QtWidgets.QPushButton(self.centralwidget)
        self.boton.setGeometry(QtCore.QRect(10, 60, 591, 51))
        self.boton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.boton.setObjectName("boton")
        self.boton1 = QtWidgets.QPushButton(self.centralwidget)
        self.boton1.setGeometry(QtCore.QRect(620, 20, 251, 23))
        self.boton1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.boton1.setObjectName("boton1")
        self.combox = QtWidgets.QComboBox(self.centralwidget)
        self.combox.setGeometry(QtCore.QRect(620, 90, 251, 22))
        self.combox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.combox.setObjectName("combox")
        self.label1 = QtWidgets.QTextEdit(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 120, 171, 31))
        self.label1.setStyleSheet("font: 7pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.label1.setObjectName("label1")
        self.E = QtWidgets.QTextEdit(self.centralwidget)
        self.E.setGeometry(QtCore.QRect(190, 120, 51, 31))
        self.E.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 7pt \"MS Shell Dlg 2\";")
        self.E.setObjectName("E")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 912, 21))
        self.menubar.setObjectName("menubar")
        self.menuOp = QtWidgets.QMenu(self.menubar)
        self.menuOp.setObjectName("menuOp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuOp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Ingrese la cantidad de pedidos </span></p></body></html>"))
        self.boton.setText(_translate("MainWindow", "Combinar"))
        self.boton1.setText(_translate("MainWindow", "importar excel"))
        self.label1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">error</span></p></body></html>"))
        self.E.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">0</span></p></body></html>"))
        self.menuOp.setTitle(_translate("MainWindow", "op"))
